Projekt2/Pages/Klient/EditAccount.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Projekt2.Models;
using System.Security.Claims;

namespace Projekt2.Pages.Klient
{
    public class EditAccountModel : PageModel
    {
        private readonly MyDbContext _context;
        private readonly IHttpContextAccessor _httpContextAccessor;

        [BindProperty]
        public Client Client { get; set; }

        public EditAccountModel(MyDbContext context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            _httpContextAccessor = httpContextAccessor;
        }

        public List<Product> PromotionalProducts { get; set; }

        public void OnGet()
        {
            PromotionalProducts = _context.Products.Include(p => p.Promotion).Where(p => p.Promotion != null).ToList();

            var userName = _httpContextAccessor.HttpContext.User.Identity.Name;
            Client = _context.Clients.FirstOrDefault(c => c.Name == userName);
        }

        public IActionResult OnPost()
        {
            var existingClient = _context.Clients.FirstOrDefault(c => c.Id == Client.Id);

            if (existingClient != null)
            {
                existingClient.Name = Client.Name;
                existingClient.LastName = Client.LastName;
                existingClient.Email = Client.Email;
                if (!string.IsNullOrEmpty(Client.Phone))
                {
                    existingClient.Phone = Client.Phone;
                }

                _context.Clients.Update(existingClient);
                _context.SaveChanges();

                return RedirectToPage("/Klient/MyAccount");
            }
            else
            {
                ModelState.AddModelError("", "Nie znaleziono klienta.");
                return Page();
            }
        }


    }
}

Projekt2/Pages/Klient/MyAccount.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Projekt2.Models;
using System.Security.Claims;

namespace Projekt2.Pages.Klient
{
    public class MyAccountModel : PageModel
    {
        private readonly MyDbContext _context;
        public Client Client { get; set; }
        public List<Order> Orders { get; set; }
        public List<Product> PromotionalProducts { get; set; }

        public MyAccountModel(MyDbContext context)
        {
            _context = context;
        }

        public void OnGet()
        {
            PromotionalProducts = _context.Products.Include(p => p.Promotion).Where(p => p.Promotion != null).ToList();

            if (!User.Identity.IsAuthenticated)
            {
                Response.Redirect("/Klient/Login");
                return;
            }

            var name = User.FindFirst(ClaimTypes.Name)?.Value;
            Client = _context.Clients.FirstOrDefault(c => c.Name == name);

            if (Client != null)
            {
                Orders = _context.Orders.Where(o => o.Client.Id == Client.Id).ToList();
            }
        }
    }
}

Projekt2/Pages/Klient/Zamowienia.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Projekt2.Models;

namespace Projekt2.Pages.Klient
{
    public class ZamowieniaModel : PageModel
    {
        private readonly MyDbContext _context;
        private readonly IHttpContextAccessor _httpContextAccessor;
        public List<Order> Orders { get; set; }
        public List<Product> PromotionalProducts { get; set; }

        public ZamowieniaModel(MyDbContext context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            _httpContextAccessor = httpContextAccessor;

            Orders = new List<Order>();
        }

        public void OnGet()
        {
            PromotionalProducts = _context.Products.Include(p => p.Promotion).Where(p => p.Promotion != null).ToList();

            var userName = _httpContextAccessor.HttpContext.User.Identity.Name;
            var client = _context.Clients.FirstOrDefault(c => c.Name == userName);

            if (client != null)
            {
                Orders = _context.Orders.Where(o => o.Client.Id == client.Id).ToList();
            }
        }

        public IActionResult OnPostCancelOrder(int orderId)
        {
            var order = _context.Orders.FirstOrDefault(o => o.Id == orderId);

            if (order != null)
            {
                order.Status = "Anulowane";
                _context.Orders.Update(order);
                _context.SaveChanges();

                var userName = _httpContextAccessor.HttpContext.User.Identity.Name;
                var client = _context.Clients.FirstOrDefault(c => c.Name == userName);

                if (client != null)
                {
                    Orders = _context.Orders.Where(o => o.Client.Id == client.Id).ToList();
                }

                return RedirectToPage();
            }

            return NotFound();
        }

    }
}

Projekt2/Pages/Klient/ZamowienieSzczegoly.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Projekt2.Models;

namespace Projekt2.Pages.Klient
{
    public class ZamowienieSzczegolyModel : PageModel
    {
        private readonly MyDbContext _context;
        public Order Order { get; set; }
        public List<OrderItem> OrderItems { get; set; }
        public List<Product> PromotionalProducts { get; set; }

        public ZamowienieSzczegolyModel(MyDbContext context)
        {
            _context = context;
        }

        public void OnGet(int orderId)
        {
            PromotionalProducts = _context.Products.Include(p => p.Promotion).Where(p => p.Promotion != null).ToList();

            Order = _context.Orders.FirstOrDefault(o => o.Id == orderId);
            if (Order != null)
            {
                OrderItems = _context.OrderItems.Where(oi => oi.OrderId == orderId).Include(oi => oi.Product).ToList();
            }
        }
    }
}

Projekt2/Pages/Klient/EditAccount.cshtml
@page
@model Projekt2.Pages.Klient.EditAccountModel
@{
    ViewData["Title"] = "Edycja danych";
}

<p>
    <a href="/Index" id="sciezka">Strona główna</a> &gt; <a href="/Klient/MyAccount" id="sciezka">Moje konto</a> &gt; <a href="/Klient/EditAccount" id="sciezka">Edycja danych</a>
</p>

<div class="container mt-5">
    <div class="card">
        <div class="card-header">
            <h5>Edytuj dane</h5>
        </div>
        <div class="card-body">
            <form method="post">
                <input asp-for="Client.Id" type="hidden" />
                <div class="form-group">
                    <label>Imię</label>
                    <input type="text" asp-for="Client.Name" class="form-control" />
                </div>
                <div class="form-group">
                    <label>Nazwisko</label>
                    <input type="text" asp-for="Client.LastName" class="form-control" />
                </div>
                <div class="form-group">
                    <label>Email</label>
                    <input type="email" asp-for="Client.Email" class="form-control" />
                </div>
                <div class="form-group mb-3">
                    <label>Telefon</label>
                    <input type="tel" asp-for="Client.Phone" class="form-control" />
                </div>
                <div class="mb-3">
                    <button type="submit" class="btn btn-primary">Zaktualizuj dane</button>
                </div>
            </form>
        </div>
    </div>
</div>

<style>
    #sciezka {
        color: black;
    }

        #sciezka:hover {
            text-decoration: underline;
        }
</style>

Projekt2/Pages/Klient/Login.cshtml
@page
@model Projekt2.Pages.Klient.LoginModel
@{
	ViewData["Title"] = "Logowanie";

    <div class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-md-6">
                <h1 class="text-center mb-4">Logowanie</h1>
                <form method="post" asp-page-handler="OnPostAsync">
                    <div asp-validation-summary="All" class="text-danger"></div>

                    <div class="form-group mb-3">
                        <label for="email">E-mail</label>
                        <input type="email" class="form-control" name="Email" maxlength="30" placeholder="E-mail" required />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>

                    <div class="form-group mb-5">
                        <label for="password">Hasło</label>
                        <input type="password" class="form-control" id="password" name="Password" minlength="3" maxlength="20" placeholder="Hasło" required />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>

                    <button type="submit" class="btn btn-primary btn-block mb-5">Zaloguj się</button>
                </form>
            </div>
        </div>
    </div>

}

Projekt2/Pages/Klient/Logout.cshtml
@page
@model Projekt2.Pages.Klient.LogoutModel
@{
	ViewData["Title"] = "Wylogowanie";
}

Projekt2/Pages/Klient/MyAccount.cshtml
@page
@model Projekt2.Pages.Klient.MyAccountModel
@{
    ViewData["Title"] = "Moje konto";
}

<p>
    <a href="/Index" id="sciezka">Strona główna</a> &gt; <a href="/Klient/MyAccount" id="sciezka">Moje konto</a>
</p>

<div class="container mt-5">
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h5>Dane klienta</h5>
                </div>
                <div class="card-body">
                    <p>Imię: @Model.Client.Name</p>
                    <p>Nazwisko: @Model.Client.LastName</p>
                    <p>Email: @Model.Client.Email</p>
                    <p>Telefon: 
                        @if (string.IsNullOrEmpty(Model.Client.Phone))
                        {
                            <span>Brak</span>
                        }
                        else
                        {
                            <span>@Model.Client.Phone</span>
                        }
                    </p>
                    <a asp-page="/Klient/EditAccount" class="btn btn-primary">Edytuj dane</a>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h5>Zamówienia</h5>
                </div>
                <div class="card-body">
                    <p>Ilość złożonych zamówień: @Model.Orders.Count</p>
                    <ul class="list-group">
                        @foreach (var order in Model.Orders)
                        {
                            <li class="list-group-item">
                                <a asp-page="/Klient/ZamowienieSzczegoly" asp-route-orderId="@order.Id" id="zamowienie">Zamówienie #@order.Id</a> - @order.Status
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    #sciezka, #zamowienie {
        color: black;
    }

    #sciezka:hover {
        text-decoration: underline;
    }

    #zamowienie:hover
    {
        text-decoration: underline;
    }
</style>

Projekt2/Pages/Klient/Register.cshtml
@page
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model Projekt2.Pages.Klient.RegisterModel
@{
	ViewData["Title"] = "Zarejestruj się";

	<h1>Rejestracja</h1>

	<form method="post" class="needs-validation" novalidate>

		@if (TempData["SuccessMessage"] != null)
		{
			<div class="alert alert-success">
				@TempData["SuccessMessage"]
			</div>
		}

		<span asp-validation-summary="All"></span>
		<div class="mb-3">
			<label for="name" class="form-label">Imię</label>
			<input type="text" class="form-control" id="name" name="NewClient.Name" maxlength="20" placeholder="Imię" required />
			<span asp-validation-for="NewClient.Name" class="text-danger"></span>
		</div>

		<div class="mb-3">
			<label for="lastName" class="form-label">Nazwisko</label>
			<input type="text" class="form-control" id="lastName" name="NewClient.LastName" maxlength="50" placeholder="Nazwisko" required />
			<span asp-validation-for="NewClient.LastName" class="text-danger"></span>
		</div>

		<div class="mb-3">
			<label for="email" class="form-label">E-mail</label>
			<input type="email" class="form-control" id="email" name="NewClient.Email" maxlength="30" placeholder="E-mail" required />
			<span asp-validation-for="NewClient.Email" class="text-danger"></span>

		</div>

		<div class="mb-3">
			<label for="phone" class="form-label">Telefon (pole opcjonalne)</label>
			<input type="text" class="form-control" id="phone" name="NewClient.Phone" maxlength="20" placeholder="Numer telefonu" />
			<span asp-validation-for="NewClient.Phone" class="text-danger"></span>
		</div>

		<div class="mb-3">
			<label for="password" class="form-label">Hasło</label>
			<input type="password" class="form-control" id="password" name="NewClient.Password" minlength="3" maxlength="20" placeholder="Hasło" required />
			<span asp-validation-for="NewClient.Password" class="text-danger"></span>
		</div>

		<button type="submit" class="btn btn-primary mb-5">Załóż konto</button>
	</form>


}

Projekt2/Pages/Klient/Zamowienia.cshtml
@page
@model Projekt2.Pages.Klient.ZamowieniaModel
@{
    ViewData["Title"] = "Zamówienia";
}

<p>
    <a href="/Index" id="sciezka">Strona główna</a> &gt; <a href="/Klient/MyAccount" id="sciezka">Moje konto</a> &gt; <a href="/Klient/Zamowienia" id="sciezka">Zamówienia</a>
</p>

@if (Model.Orders.Any())
{
    <h2>Twoje zamówienia</h2>

    <table class="table">
        <thead>
            <tr>
                <th>Numer zamówienia</th>
                <th>Data zamówienia</th>
                <th>Status</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var order in Model.Orders)
            {
                <tr>
                    <td>@order.Id</td>
                    <td>@order.OrderDate.ToString("d")</td>
                    <td>@order.Status</td>
                    <td>
                        @if (order.Status == "Nowe")
                        {
                            <form method="post" asp-page-handler="CancelOrder">
                                <input type="hidden" name="orderId" value="@order.Id" />
                                <button type="submit" class="btn btn-danger">Anuluj zamówienie</button>
                            </form>
                        }
                    </td>
                    <td>
                        <a asp-page="/Klient/ZamowienieSzczegoly" asp-route-orderId="@order.Id" class="btn btn-primary">Szczegóły</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div class="text-center mb-3">
        <h4>Brak zamówień</h4>
    </div>
}

<style>
    #sciezka {
        color: black;
    }

        #sciezka:hover {
            text-decoration: underline;
        }
</style>

Projekt2/Pages/Klient/ZamowienieSzczegoly.cshtml
@page
@using System.Globalization;
@model Projekt2.Pages.Klient.ZamowienieSzczegolyModel
@{
	ViewData["Title"] = "Szczegóły zamówienia";
}

<p>
    <a href="/Index" id="sciezka">Strona główna</a> &gt; <a href="/Klient/MyAccount" id="sciezka">Moje konto</a> &gt; <a href="/Klient/Zamowienia" id="sciezka">Zamówienia</a> &gt; Zamówienie #@Model.Order.Id
</p>

<h2>Szczegóły zamówienia</h2>

<p>Numer zamówienia: @Model.Order.Id</p>
<p>Data zamówienia: @Model.Order.OrderDate.ToString("d")</p>
<p>Status: @Model.Order.Status</p>

<table class="table">
    <thead>
        <tr>
            <th>Zdjęcie</th>
            <th>Nazwa Produktu</th>
            <th>Ilość</th>
            <th>Cena</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.OrderItems)
        {
            <tr>
                <td><img src="~/images/@item.Product.ImagePath" id="obr" alt="Obrazek"></td>
                <td>@item.Product.Name</td>
                <td>@item.Quantity</td>
                <td>@item.PriceAtPurchase.ToString("F2") zł</td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="2">Koszt transportu:</td>
            <td></td>
            <td>@Model.Order.Transport zł</td>
        </tr>
        <tr>
            <td colspan="2">Całkowity koszt:</td>
            <td></td>
            <td>
                @{
                    decimal totalCost = Model.OrderItems.Sum(item => item.PriceAtPurchase * item.Quantity) + Model.Order.Transport;
                }
                @(totalCost.ToString("F2")) zł
            </td>
        </tr>
    </tfoot>
</table>

<style>
    #sciezka {
        color: black;
    }

    #sciezka:hover {
        text-decoration: underline;
    }
</style>