Projekt2/Models/Promotion.cs
namespace Projekt2.Models
{
    public class Promotion
    {
        public int Id { get; set; }
        public int DiscountPercent { get; set; }
        public int ProductId { get; set; }
        public Product Product { get; set; }
    }
}

Projekt2/Models/User.cs
using System.ComponentModel.DataAnnotations;

namespace Projekt2.Models
{
	public class User
	{
		public int Id { get; set; }

		[Required(ErrorMessage = "Nazwa użytkownika jest wymagana.")]
		public string Username { get; set; }

		[Required(ErrorMessage = "Hasło jest wymagane.")]
		public string Password { get; set; }

		[Required(ErrorMessage = "Imię jest wymagane.")]
		public string Name { get; set; }

		[Required(ErrorMessage = "Nazwisko jest wymagane.")]
		public string Lastname { get; set; }

		[Required(ErrorMessage = "Adres e-mail jest wymagany.")]
		[EmailAddress(ErrorMessage = "Nieprawidłowy adres e-mail.")]
		public string Email { get; set; }

	}
}

Projekt2/Pages/Admin/Klienci.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Projekt2.Models;

namespace Projekt2.Pages.Admin
{
    public class KlienciModel : PageModel
    {
        private readonly MyDbContext _context;

        public List<Product> PromotionalProducts { get; set; }

        public KlienciModel(MyDbContext context)
        {
            _context = context;
        }

        public List<Client> Clients { get; set; }

        public void OnGet()
        {
            Clients = _context.Clients.ToList();
            PromotionalProducts = _context.Products.Include(p => p.Promotion).Where(p => p.Promotion != null).ToList();
        }
    }
}

Projekt2/Pages/Admin/Promotions.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Projekt2.Models;

namespace Projekt2.Pages.Admin
{
    public class PromotionsModel : PageModel
    {
        private readonly MyDbContext _context;
        public List<Product> Products { get; set; }

        [BindProperty]
        public int? SelectedProductId { get; set; }

        [BindProperty]
        public int DiscountPercent { get; set; }

        public PromotionsModel(MyDbContext context)
        {
            _context = context;
        }

        public async Task OnGetAsync()
        {
            Products = await _context.Products.Include(p => p.Promotion).ToListAsync();
        }

        public async Task<IActionResult> OnPostAddAsync()
        {
            var product = await _context.Products.FindAsync(SelectedProductId);
            if (product != null && product.Promotion == null)
            {
                product.Promotion = new Promotion
                {
                    DiscountPercent = DiscountPercent
                };
                await _context.SaveChangesAsync();
            }

            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostRemoveAsync(int promotionId)
        {
            var promotion = await _context.Promotions.FindAsync(promotionId);

            if (promotion != null)
            {
                var product = await _context.Products.FirstOrDefaultAsync(p => p.Promotion == promotion);

                if (product != null)
                {
                    product.Promotion = null;
                }

                _context.Promotions.Remove(promotion);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage();
        }

    }
}

Projekt2/Pages/Admin/SzczegolyUsers.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Projekt2.Models;

namespace Projekt2.Pages.Admin
{
    public class SzczegolyUsersModel : PageModel
    {
        private readonly MyDbContext _context;

        public SzczegolyUsersModel(MyDbContext context)
        {
            _context = context;
        }

        public User Users { get; set; }

        public void OnGet(int userId)
        {
            Users = _context.Users.FirstOrDefault(u => u.Id == userId);
        }
    }
}

Projekt2/Pages/Admin/Klienci.cshtml
@page
@model Projekt2.Pages.Admin.KlienciModel
@{
	ViewData["Title"] = "Klienci";
}

<h2>Klienci</h2>

<table class="table">
    <thead>
        <tr>
            <th>Imię</th>
            <th>Nazwisko</th>
            <th>Email</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var client in Model.Clients)
        {
            <tr>
                <td>@client.Name</td>
                <td>@client.LastName</td>
                <td>@client.Email</td>
                <td>
                    <a href="@Url.Page("SzczegolyKlienta", new { clientId = client.Id })" class="btn btn-primary">Pokaż szczegóły</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Projekt2/Pages/Admin/Login.cshtml
@page
@model Projekt2.Pages.Admin.LoginModel
@{
	ViewData["Title"] = "Admin - Logowanie";
}

<div class="container border" style="padding: 20px;">
    <form method="post">
        <div class="form-group row mb-2">
            <div class="col-2">
                <label for="username">Login</label>
            </div>
            <div class="col-5">
                <input type="text" id="username" name="Username" class="form-control" />
            </div>
            <span class="text-danger" asp-validation-for="Username"></span>
        </div>
        <div class="form-group row mb-3">
            <div class="col-2">
                <label for="password">Hasło</label>
            </div>
            <div class="col-5">
                <input type="password" id="password" name="Password" class="form-control" />
            </div>
            <span class="text-danger" asp-validation-for="Password"></span>
        </div>
        <div class="form-group row mb-3">
            <div class="col-2">
                <input type="submit" class="btn btn-primary" value="Zaloguj" />
            </div>
        </div>

	</form>
</div>

Projekt2/Pages/Admin/Logout.cshtml
@page
@model Projekt2.Pages.Admin.LogoutModel
@{
	ViewData["Title"] = "Admin - Wylogowanie";
}

Projekt2/Pages/Admin/Promotions.cshtml
@page
@model Projekt2.Pages.Admin.PromotionsModel
@{
	ViewData["Title"] = "Zarządzaj promocjami";

    var promotionalProducts = Model.Products.Where(p => p.Promotion != null).ToList();
}

<h1>Zarządzaj promocjami</h1>

<form method="post" asp-page-handler="Add" class="mb-3">
    <div class="form-group mb-1">
        <label for="SelectedProductId">Produkt:</label>
        <select asp-for="SelectedProductId" asp-items="@(new SelectList(Model.Products.Where(p => p.Promotion == null), "Id", "Name"))" class="form-control"></select>
    </div>
    <div class="form-group mb-3">
        <label for="DiscountPercent">Zniżka (%):</label>
        <input asp-for="DiscountPercent" type="number" min="5" max="100" step="1" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary mb-3">Dodaj do promocji</button>
</form>

@if (!promotionalProducts.Any())
{
    <p>Brak produktów w promocji</p>
}
else
{
    <h2>Produkty w promocji</h2>

    <table class="table">
        <thead>
            <tr>
                <th>Nazwa</th>
                <th>Zniżka</th>
                <th>Akcje</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var product in promotionalProducts)
            {
                <tr>
                    <td>@product.Name</td>
                    <td>@product.Promotion.DiscountPercent %</td>
                    <td>
                        <form method="post">
                            <input type="hidden" name="promotionId" value="@product.Promotion.Id" />
                            <button type="submit" asp-page-handler="Remove" class="btn btn-danger">Usuń z promocji</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

Projekt2/Pages/Admin/Register.cshtml
@page
@using Microsoft.AspNetCore.Mvc.Rendering
@model Projekt2.Pages.RegisterModel
@{
	ViewData["Title"] = "Zarejestruj się";

    <h1>Rejestracja</h1>

    <form method="post">
        @if (TempData["SuccessMessage"] != null)
        {
            <div class="alert alert-success">
                @TempData["SuccessMessage"]
            </div>
        }
        <div class="form-group">
            <label for="username">Login:</label>
            <input type="text" class="form-control" id="username" name="NewUser.Username" />
            <span asp-validation-for="NewUser.Username" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label for="password">Hasło:</label>
            <input type="password" class="form-control" id="password" name="NewUser.Password" />
            <span asp-validation-for="NewUser.Password" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label for="name">Imię:</label>
            <input type="text" class="form-control" id="name" name="NewUser.Name" />
            <span asp-validation-for="NewUser.Name" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label for="lastname">Nazwisko:</label>
            <input type="text" class="form-control" id="lastname" name="NewUser.Lastname" />
            <span asp-validation-for="NewUser.Lastname" class="text-danger"></span>
        </div>

        <div class="form-group mb-5">
            <label for="email">E-mail:</label>
            <input type="email" class="form-control" id="email" name="NewUser.Email" />
            <span asp-validation-for="NewUser.Email" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-primary mb-5">Załóż konto</button>
    </form>


}

Projekt2/Pages/Admin/SzczegolyKlienta.cshtml
@page
@model Projekt2.Pages.Admin.SzczegolyKlientaModel
@{
    ViewData["Title"] = "Szczegóły Klienta";
}

<p>
    <a href="/Admin/Klienci" id="sciezka">Klienci</a> &gt; @Model.Client.Name @Model.Client.LastName
</p>

<div class="container mt-5">
    <div class="card">
        <div class="card-header">
            <h2 class="mb-0">Szczegóły Klienta: @Model.Client.Name @Model.Client.LastName</h2>
        </div>
        <div class="card-body">
            <p class="card-text"><strong>E-mail:</strong> @Model.Client.Email</p>
            <p class="card-text">
                <strong>Numer telefonu:</strong>
                @if (string.IsNullOrEmpty(Model.Client.Phone))
                {
                    <span>Brak</span>
                }
                else
                {
                    <span>@Model.Client.Phone</span>
                }
            </p>
            <p class="card-text"><strong>Liczba zamówień:</strong> @Model.OrderCount</p>
        </div>
    </div>
</div>

<style>
    #sciezka {
        color: black;
    }

        #sciezka:hover {
            text-decoration: underline;
        }
</style>

Projekt2/Pages/Admin/SzczegolyUsers.cshtml
@page
@model Projekt2.Pages.Admin.SzczegolyUsersModel
@{
    ViewData["Title"] = "Szczegóły użytkownika";
}

<p>
    <a href="/Admin/Users" id="sciezka">Użytkownicy</a> &gt; @Model.Users.Username
</p>

<div class="container mt-5">
    <div class="card">
        <div class="card-header">
            <h2 class="mb-0">Szczegóły użytkownika: @Model.Users.Username</h2>
        </div>
        <div class="card-body">
            <p class="card-text">
                <strong>Imię: </strong> @Model.Users.Name
            </p>
            <p class="card-text">
                <strong>Nazwisko:</strong> @Model.Users.Lastname
            </p>
            <p class="card-text">
                <strong>E-mail:</strong> @Model.Users.Email
            </p>
        </div>
    </div>
</div>

<style>
    #sciezka {
        color: black;
    }

        #sciezka:hover {
            text-decoration: underline;
        }
</style>

Projekt2/Pages/Admin/Users.cshtml
@page
@model Projekt2.Pages.Admin.UsersModel
@{
    ViewData["Title"] = "Użytkownik";
}

@if (!String.IsNullOrEmpty(Model.Message))
{
    <div class="alert alert-success">
        @Model.Message
    </div>
}

<h2>Użytkownik</h2>

<table class="table">
    <thead>
        <tr>
            <th>Login</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model.Users)
        {
            <tr>
                <td>@user.Username</td>
                <td>
                    <a href="@Url.Page("SzczegolyUsers", new { userId = user.Id })" class="btn btn-primary">Pokaż szczegóły</a>
                </td>
                <td>
                    @if (user.Id != 1 && user.Username != "admin")
                    {
                        <form method="post">
                            <input type="hidden" name="userId" value="@user.Id" />
                            <button type="submit" asp-page-handler="DeleteUser" asp-route-id="@user.Id" class="btn btn-danger">Usuń</button>
                        </form>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

Projekt2/Pages/Admin/ZamowieniaAdmin.cshtml
@page
@model Projekt2.Pages.Admin.ZamowieniaAdminModel
@{
    ViewData["Title"] = "Zamówienia - Admin";
}

<h2>Zamówienia</h2>

<table class="table">
    <thead>
        <tr>
            <th>Numer zamówienia</th>
            <th>Data zamówienia</th>
            <th>Status</th>
            <th>Klient</th>
            <th>Szczegóły zamówienia</th>
            <th>Zmień status</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var order in Model.Orders)
        {
            <tr>
                <td>#@order.Id</td>
                <td>@order.OrderDate.ToString("d")</td>
                <td>@order.Status</td>
                <td>@order.Client.Name</td>
                <td>
                    <ul>
                        @foreach (var item in order.OrderItems)
                        {
                            <li>@item.Product.Name, Ilość: @item.Quantity</li>
                        }
                    </ul>
                </td>
                <td>
                    <form method="post" asp-page-handler="ChangeStatus">
                        <input type="hidden" name="orderId" value="@order.Id" />
                        <select name="newStatus">
                            <option value="Nowe">Nowe</option>
                            <option value="W trakcie">W trakcie</option>
                            <option value="Zrealizowane">Zrealizowane</option>
                            <option value="Anulowane">Anulowane</option>
                        </select>
                        <button type="submit" class="btn btn-primary">Zmień status</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>